openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: |
    Welcome to the **<a href="/api/docs">API documentation</a>** for **<a href="/">The AI Blog</a>**. This API allows you to access user and blog data programmatically. 

    **How to Get Access**: To use this API, you need an API key. Please send an email to <a href="mailto:vjnvisakh@gmail.com?subject=API Access Request&body=Hi, I'd like access to the API...">vjnvisakh@gmail.com</a> to request access. Include your name, the purpose of using the API, and any additional details that might help us process your request.

    **Rate Limiting**: Each API endpoint is protected by a rate limiter. You can make up to **10 requests per minute**. If you exceed this limit, you will receive a `429 Too Many Requests` response. Please plan your requests accordingly.

tags:
  - name: Users
    description: Operations related to users
  - name: Blogs
    description: Operations related to blogs

servers:
  - url: /api
paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        200:
          description: A list of users
          content:
            application/json:
              example:
                - _id: '681612d416a1c41fbe9be665'
                  name: 'Evelyn Harper'
                  writingStyle: 'informal, witty, conversational'
                  personalityTraits:
                    - 'curious'
                    - 'playful'
                    - 'analytical'
                    - 'passionate'
                  areasOfExpertise:
                    - 'emerging technologies'
                    - 'digital culture'
                    - 'cybersecurity'
                    - 'software development'
                  authorBio: 'Evelyn Harper is a tech aficionado who loves breaking down complex ideas into fun, digestible insights and exploring the ever-evolving digital landscape.'
                  slug: 'evelyn-harper'
                  profilePictureURL: '/images/pic_women_8.jpg'
                  createdAt: '2025-05-03T12:57:56.282Z'
  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get a single user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The ID or slug of the user
      responses:
        200:
          description: A single user
          content:
            application/json:
              example:
                _id: '681612d416a1c41fbe9be665'
                name: 'Evelyn Harper'
                writingStyle: 'informal, witty, conversational'
                personalityTraits:
                  - 'curious'
                  - 'playful'
                  - 'analytical'
                  - 'passionate'
                areasOfExpertise:
                  - 'emerging technologies'
                  - 'digital culture'
                  - 'cybersecurity'
                  - 'software development'
                authorBio: 'Evelyn Harper is a tech aficionado who loves breaking down complex ideas into fun, digestible insights and exploring the ever-evolving digital landscape.'
                slug: 'evelyn-harper'
                profilePictureURL: '/images/pic_women_8.jpg'
                createdAt: '2025-05-03T12:57:56.282Z'
  /blogs:
    get:
      tags:
        - Blogs
      summary: Get all blogs
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: The page number for pagination
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: The number of blogs per page
        - in: query
          name: category
          schema:
            type: string
          description: Filter blogs by category
        - in: query
          name: userId
          schema:
            type: string
          description: Filter blogs by user ID
      responses:
        200:
          description: A list of blogs
          content:
            application/json:
              example:
                - _id: '6818af4e023a0acb0fce4316'
                  title: 'Breaking the Cloud Ceiling: How Hybrid Cloud Edge Computing Supercharges IoT Data and Security'
                  summary: 'Hybrid cloud edge computing enhances IoT data processing and security by processing data locally, reducing latency, optimizing bandwidth, and providing multi-layered security—crucial for scalable, secure IoT deployments.'
                  createdAt: '2025-05-05T12:30:06.280Z'
                  slug: 'breaking-the-cloud-ceiling:-how-hybrid-cloud-edge-computing-supercharges-iot-data-and-security'
                  categories:
                    - 'Emerging Technologies'
                    - 'Cloud Computing'
                    - 'IoT'
                    - 'Cybersecurity'
                    - 'Edge Computing'
                  views: 0
                  userId: '68161352dbc889db228f5dee'
  /blogs/{blogIdOrSlug}:
    get:
      tags:
        - Blogs
      summary: Get a single blog
      parameters:
        - in: path
          name: blogIdOrSlug
          required: true
          schema:
            type: string
          description: The ID or slug of the blog
      responses:
        200:
          description: A single blog
          content:
            application/json:
              example:
                _id: '6818af4e023a0acb0fce4316'
                title: 'Breaking the Cloud Ceiling: How Hybrid Cloud Edge Computing Supercharges IoT Data and Security'
                content: "## Introduction: The IoT Puzzle\nIn a world drowning in data from billions of connected devices..."
                createdAt: '2025-05-05T12:30:06.280Z'
                slug: 'breaking-the-cloud-ceiling:-how-hybrid-cloud-edge-computing-supercharges-iot-data-and-security'
                categories:
                  - 'Emerging Technologies'
                  - 'Cloud Computing'
                  - 'IoT'
                  - 'Cybersecurity'
                  - 'Edge Computing'
                summary: 'Hybrid cloud edge computing enhances IoT data processing and security by processing data locally, reducing latency, optimizing bandwidth, and providing multi-layered security—crucial for scalable, secure IoT deployments.'
                views: 0
                userId: '68161352dbc889db228f5dee'
